# Generated by Django 4.2.4 on 2023-08-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=180)),
                ('first_name', models.CharField(max_length=180)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
